server:
  # 내장 톰캣 포트번호
  port: 8080

spring:
  application:
    name: app

  mvc:
    # 404 오류 커스텀을 위한 작업
    # DispatcherServlet.javA에 throwExceptionIfNoHandlerFound 필드값이 true일때
    # throw new NoHandlerFoundException를 처리하기 때문에
    # 해당 값 true로 지정해주고 RestControllerAdvice에서 해당 에러 캐치 하면됨
    throw-exception-if-no-handler-found: true

  web:
    resources:
      # 매핑 컨트롤러가 없을경우 resource 경로로 판단하는 부분을 차단
      # resource에 대한 정의는 WebMvcConfiguration에서 처리
      add-mappings: false

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: 'jdbc:h2:mem:testdb'
      username: sa
      password:

  # 임베디드 h2 콘솔을 사용하기 위한 정의
  h2:
    console:
      # console 사용 여부
      enabled: true
      # 접속주소(http://localhost:{port}/h2-console)
      path: /h2-console

  # 업로드 관련 설정
  servlet:
    multipart:
      #업로드 파일 용량 제한
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:/uploads/images/

logging:
  level:
    com.framework.app: debug
    org.springframework.web: debug
    root: info

springdoc:
  packages-to-scan: com.framework.app
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    enabled: true
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
